package com.novoa.videogames.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Consoles")
public class Console {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String consoleId;
    @DynamoDBAttribute
    private String consoleName;
    @DynamoDBAttribute
    private String minPrice;
    @DynamoDBAttribute
    private String maxPrice;
    @DynamoDBAttribute
    private String discount;
}
